# Generated by Django 4.2.7 on 2025-10-02 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("choice", "选择题"),
                            ("fill", "填空题"),
                            ("short_answer", "简答题"),
                        ],
                        max_length=20,
                        verbose_name="题型",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="题目内容")),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="选择题选项，JSON格式",
                        null=True,
                        verbose_name="选项",
                    ),
                ),
                ("answer", models.TextField(verbose_name="标准答案")),
                ("explanation", models.TextField(verbose_name="答案解析")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("basic", "基础"),
                            ("medium", "中等"),
                            ("advanced", "拓展"),
                        ],
                        max_length=20,
                        verbose_name="难度",
                    ),
                ),
                (
                    "is_ai_generated",
                    models.BooleanField(default=False, verbose_name="是否AI生成"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "练习题",
                "verbose_name_plural": "练习题",
                "db_table": "exercises_exercise",
            },
        ),
        migrations.CreateModel(
            name="AnswerRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.TextField(verbose_name="用户答案")),
                (
                    "is_correct",
                    models.BooleanField(blank=True, null=True, verbose_name="是否正确"),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, help_text="0-100", null=True, verbose_name="得分"
                    ),
                ),
                (
                    "ai_feedback",
                    models.TextField(blank=True, verbose_name="AI批改反馈"),
                ),
                (
                    "time_spent",
                    models.IntegerField(
                        default=0, help_text="秒", verbose_name="答题耗时"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_records",
                        to="exercises.exercise",
                        verbose_name="题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "答题记录",
                "verbose_name_plural": "答题记录",
                "db_table": "exercises_answerrecord",
            },
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["course"], name="exercises_e_course__1cd70c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["question_type"], name="exercises_e_questio_5d29a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["difficulty"], name="exercises_e_difficu_1e38ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answerrecord",
            index=models.Index(
                fields=["user", "exercise"], name="exercises_a_user_id_69c03b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answerrecord",
            index=models.Index(
                fields=["submitted_at"], name="exercises_a_submitt_732117_idx"
            ),
        ),
    ]
