# Generated by Django 4.2.7 on 2025-10-02 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="学科名称")),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("chinese", "语文"),
                            ("math", "数学"),
                            ("english", "英语"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="学科代码",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="学科图标"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="学科描述")),
                ("order", models.IntegerField(default=0, verbose_name="排序序号")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
            options={
                "verbose_name": "学科",
                "verbose_name_plural": "学科",
                "db_table": "courses_subject",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("grade1", "初一"),
                            ("grade2", "初二"),
                            ("grade3", "初三"),
                        ],
                        max_length=20,
                        verbose_name="年级",
                    ),
                ),
                ("course_number", models.IntegerField(verbose_name="课程序号")),
                ("title", models.CharField(max_length=200, verbose_name="课程标题")),
                ("outline", models.TextField(verbose_name="课程大纲")),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="逗号分隔",
                        max_length=500,
                        verbose_name="关键词",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="courses/",
                        verbose_name="封面图片",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "基础"),
                            ("medium", "进阶"),
                            ("hard", "提高"),
                        ],
                        max_length=20,
                        verbose_name="难度级别",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序序号")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="courses.subject",
                        verbose_name="学科",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "db_table": "courses_course",
                "ordering": ["subject", "grade", "course_number"],
            },
        ),
        migrations.CreateModel(
            name="StudyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开始"),
                            ("in_progress", "学习中"),
                            ("completed", "已完成"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="学习状态",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="0-100", verbose_name="进度"
                    ),
                ),
                (
                    "study_time",
                    models.IntegerField(
                        default=0, help_text="秒", verbose_name="学习时长"
                    ),
                ),
                (
                    "last_access",
                    models.DateTimeField(auto_now=True, verbose_name="最后访问时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习进度",
                "verbose_name_plural": "学习进度",
                "db_table": "courses_studyprogress",
                "indexes": [
                    models.Index(
                        fields=["status"], name="courses_stu_status_3afdea_idx"
                    )
                ],
                "unique_together": {("user", "course")},
            },
        ),
        migrations.CreateModel(
            name="KnowledgeSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="知识点总结内容")),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识点总结",
                "verbose_name_plural": "知识点总结",
                "db_table": "courses_knowledgesummary",
                "indexes": [
                    models.Index(
                        fields=["course"], name="courses_kno_course__4f0f44_idx"
                    ),
                    models.Index(
                        fields=["version"], name="courses_kno_version_ad6f4d_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["subject", "grade"], name="courses_cou_subject_223230_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["course_number"], name="courses_cou_course__5cfed0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("subject", "grade", "course_number")},
        ),
    ]
