# Generated by Django 4.2.7 on 2025-10-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="从PDF提取的课本实际文字内容，供AI参考",
                verbose_name="章节内容",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="pdf_page_range",
            field=models.CharField(
                blank=True,
                help_text="如：18-50",
                max_length=50,
                verbose_name="PDF页码范围",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="pdf_source",
            field=models.CharField(
                blank=True,
                help_text="原始PDF文件名",
                max_length=500,
                verbose_name="PDF来源",
            ),
        ),
    ]
