# Generated by Django 4.2.7 on 2025-10-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_content_course_pdf_page_range_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="course",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.CharField(
                choices=[("first", "上学期"), ("second", "下学期"), ("all", "全学年")],
                default="all",
                max_length=20,
                verbose_name="学期",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("subject", "grade", "semester", "course_number")},
        ),
    ]
