# Generated by Django 4.2.7 on 2025-10-02 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("knowledge_summary", "知识点总结"),
                            ("exercise_generation", "练习题生成"),
                            ("answer_correction", "答案批改"),
                        ],
                        max_length=50,
                        verbose_name="模板类型",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("chinese", "语文"),
                            ("math", "数学"),
                            ("english", "英语"),
                            ("all", "通用"),
                        ],
                        max_length=20,
                        verbose_name="适用学科",
                    ),
                ),
                (
                    "template_name",
                    models.CharField(max_length=100, verbose_name="模板名称"),
                ),
                (
                    "template_content",
                    models.TextField(
                        help_text="支持变量如{course_name}", verbose_name="模板内容"
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "Prompt模板",
                "verbose_name_plural": "Prompt模板",
                "db_table": "ai_services_prompttemplate",
            },
        ),
        migrations.CreateModel(
            name="PromptUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.JSONField(verbose_name="输入参数")),
                ("output_data", models.TextField(verbose_name="AI输出结果")),
                (
                    "quality_score",
                    models.IntegerField(
                        blank=True,
                        help_text="1-5分",
                        null=True,
                        verbose_name="质量评分",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="使用时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_logs",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="ai_services.prompttemplate",
                        verbose_name="模板",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt使用日志",
                "verbose_name_plural": "Prompt使用日志",
                "db_table": "ai_services_promptusagelog",
            },
        ),
        migrations.AddIndex(
            model_name="prompttemplate",
            index=models.Index(
                fields=["template_type", "subject"],
                name="ai_services_templat_0e3f7b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prompttemplate",
            index=models.Index(
                fields=["is_active"], name="ai_services_is_acti_a6fa20_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="prompttemplate",
            unique_together={("template_type", "subject", "version")},
        ),
        migrations.AddIndex(
            model_name="promptusagelog",
            index=models.Index(
                fields=["template"], name="ai_services_templat_9706c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptusagelog",
            index=models.Index(fields=["user"], name="ai_services_user_id_2d0aa0_idx"),
        ),
        migrations.AddIndex(
            model_name="promptusagelog",
            index=models.Index(
                fields=["used_at"], name="ai_services_used_at_1b416b_idx"
            ),
        ),
    ]
