# Generated by Django 4.2.7 on 2025-10-02 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("deepseek-r1", "DeepSeek-R1"),
                            ("gpt-4", "GPT-4"),
                            ("gpt-4-turbo", "GPT-4 Turbo"),
                        ],
                        max_length=50,
                        verbose_name="模型类型",
                    ),
                ),
                ("encrypted_api_key", models.TextField(verbose_name="加密的API Key")),
                (
                    "api_endpoint",
                    models.URLField(blank=True, max_length=255, verbose_name="API端点"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aiconfig",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI配置",
                "verbose_name_plural": "AI配置",
                "db_table": "users_aiconfig",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[utils.validators.validate_phone],
                        verbose_name="手机号",
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        default="上海市新北郊初级中学",
                        max_length=100,
                        verbose_name="学校名称",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("grade1", "初一"),
                            ("grade2", "初二"),
                            ("grade3", "初三"),
                        ],
                        max_length=20,
                        verbose_name="年级",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "total_study_hours",
                    models.IntegerField(default=0, verbose_name="总学习时长(秒)"),
                ),
                (
                    "continuous_days",
                    models.IntegerField(default=0, verbose_name="连续学习天数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
                "db_table": "users_userprofile",
                "indexes": [
                    models.Index(
                        fields=["user"], name="users_userp_user_id_d181df_idx"
                    ),
                    models.Index(fields=["grade"], name="users_userp_grade_90dda6_idx"),
                ],
            },
        ),
    ]
